spring:
  application.name: resilience4j-demo  # Specifies the name of the Spring application.
  jackson.serialization.indent_output: true  # Enables pretty-printing of JSON output for better readability.

management:
  endpoints.web.exposure.include:
    - '*'  # Exposes all management endpoints, making them available over HTTP.
  endpoint.health.show-details: always  # Always shows detailed information in health endpoint responses.
  health.circuitbreakers.enabled: true  # Enables health checks for circuit breakers.

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true  # Registers a health indicator for the circuit breaker.
      slidingWindowSize: 10  # Sets the size of the sliding window for measuring call outcomes.
      minimumNumberOfCalls: 5  # Minimum number of calls before the circuit breaker calculates metrics.
      permittedNumberOfCallsInHalfOpenState: 3  # Number of permitted calls when the circuit breaker is half-open.
      automaticTransitionFromOpenToHalfOpenEnabled: true  # Enables automatic transition from open to half-open state.
      waitDurationInOpenState: 5s  # Time duration the circuit breaker stays open before transitioning to half-open.
      failureRateThreshold: 50  # Threshold for failure rate percentage at which the circuit breaker opens.
      eventConsumerBufferSize: 10  # Size of the buffer for storing events generated by the circuit breaker.
